WITH OFFLINE AS(
    SELECT date_format(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE WHERE SALES_DATE LIKE '2022-03%'
)

SELECT date_format(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

union all

SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM OFFLINE
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;

