-- 코드를 입력하세요
SELECT UGU.USER_ID, UGU.NICKNAME, CONCAT(UGU.CITY, " ", UGU.STREET_ADDRESS1, " ", UGU.STREET_ADDRESS2) AS 전체주소, CONCAT(LEFT(UGU.TLNO, 3), '-', SUBSTRING(UGU.TLNO, 4, 4), '-', RIGHT(UGU.TLNO, 4)) AS 전화번호
FROM USED_GOODS_USER UGU INNER JOIN USED_GOODS_BOARD UGB ON UGU.USER_ID = UGB.WRITER_ID
GROUP BY UGB.WRITER_ID
HAVING COUNT(UGB.WRITER_ID) >= 3
ORDER BY UGU.USER_ID DESC;