WITH VALUE AS(
SELECT CRCC.DAILY_FEE, CRCC.CAR_TYPE, CRCRH.HISTORY_ID, DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 AS PERIOD,
    (CASE 
        WHEN (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 >= 90) THEN '90일 이상'
        WHEN (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 >= 30) THEN '30일 이상'
        WHEN (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 >= 7) THEN '7일 이상'
        ELSE 'NONE'
        END) AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH INNER JOIN CAR_RENTAL_COMPANY_CAR CRCC ON CRCRH.CAR_ID = CRCC.CAR_ID
WHERE CRCC.CAR_TYPE = '트럭'
)

SELECT V.HISTORY_ID, 
    ROUND(V.DAILY_FEE * ((100 - IFNULL(PLAN.DISCOUNT_RATE, 0)) / 100) * V.PERIOD, 0) AS FEE
FROM VALUE V LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN ON V.DURATION_TYPE = PLAN.DURATION_TYPE AND V.CAR_TYPE = PLAN.CAR_TYPE
ORDER BY FEE DESC, V.HISTORY_ID DESC; 