-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (SELECT ID
            FROM SKILLCODES
            WHERE CATEGORY = 'Front End' AND 
            SKILL_CODE & CODE)
ORDER BY ID;                  