-- 코드를 작성해주세요
SELECT SUM(HG.SCORE) AS SCORE, HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE INNER JOIN HR_DEPARTMENT HD ON HE.DEPT_ID = HD.DEPT_ID
                     INNER JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO
GROUP BY HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;