-- 코드를 입력하세요
WITH MAX_VIEWS AS(
    SELECT BOARD_ID, VIEWS
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
SELECT CONCAT('/home/grep/src', '/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE UGF INNER JOIN MAX_VIEWS MV ON UGF.BOARD_ID = MV.BOARD_ID
ORDER BY UGF.FILE_ID DESC;